### ISSUE TITLE
Installtion error

### ISSUE THREAD

**Issue by green-dalii** [abhikpal/p5py#1]
There is no file named "requirements.txt" in p5py.

**Comment by abhikpal** [comment]
Thanks for reporting this! I've added the correct `requirements.txt`.

I'm working on the renderer now, so complete sketches won't work but you can try running the test program by moving to the `develop` branch (and let me know if you get errors while running that).

```bash
git clone https://github.com/abhikpal/p5py
cd p5py
git checkout develop
pip install -r requirements.txt
```

and then running the test

```bash
cd tests
python test_renderer.py
```
