### ISSUE TITLE
Related Project

### ISSUE THREAD

**Issue by jonay2000** [abhikpal/p5py#2]
Dear Abhik Pal, via Daniel Shiffman i came to you after i let him know that i was working on a similar project. in your github repos it seems that p5py is in very early stages. I myself am working on a p5py library too. i have got about 20-30% of the p5js funcitonality in. i thougth i'd just let you know. maybe we could work together on it because to me it seems unnecessary to do double work. since my version uses tkinter (in stead of pyglet) i really have similar support as p5js has since i also simulate a few (and later more) of the  DOM library  (so i can create paragraphs and buttons and text inputs). please let me know what you think.

**Comment by abhikpal** [comment]
This sounds amazing!

> it seems that p5py is in very early stages.

That's true. We are working on the internal OpenGL stuff right now, so most of higher level stuff like drawing shapes, color, etc don't work. Most of the development code is on the [develop](https://github.com/abhikpal/p5py/tree/develop) branch, if you want to play around (and test things out!)

> I myself am working on a p5py library too [...] maybe we could work
> together on it

I would love to have a look :) Is the project hosted on github?

> maybe we could work together on it

Definitely! Feel free to open issues, create pull requests, and ask questions!

**Comment by jonay2000** [comment]
Thanks for your reaction, whenever i have got a stable version i'll upload. i must admit that i found that tkinter's canvas is quite slow especially when you start looking at 3d stuff. so i'm sorta half switching my code over to openGL
it might have dual funcitonality just like in p5js you can enable webGL. i'm putting about all my time into this right now meaning my version runs already kinda stable (especially the tkinter version). i have a checklist with the p5 reference and the tkinter version got about 20% in (as i said). i hope the pyglet version will go quick too since i got the tkinter framwork already. one thing that may be cool and my version already has (in tkinter and pyglet) is multiple window support (without multiple draw loops like in processing). you can just call CreateWindow() twice and then do window.select() to draw on it. might be cool to think about.

**Comment by jonay2000** [comment]
Its funny that we both started this project around the same time and got around as much done :) i'd think if we worked together it could really become a thing. i got a few friends who really hope it were a thing because they use processing.py now which isn't as good as a python-only library.

**Comment by abhikpal** [comment]
> one thing that may be cool and my version already has (in tkinter and pyglet) is multiple window support

We could look into this once we have support for most of Processing's core functionality. It shouldn't be too difficult though, as pyglet supports mutliple windows.

> i got a few friends who really hope it were a thing

You should ask them to get involved and help us test things out!

> whenever i have got a stable version i'll upload

I'm closing this thread for now, but feel free to notify me when you do the upload!
