### ISSUE TITLE
Implementation -- running sketches

### ISSUE THREAD

**Issue by jonay2000** [abhikpal/p5py#3]
I have been looking through your code and i found something i didn't use: you use decorators for the functions. i am not sure which way is the best but i do it differently. i look back in the stack and find from where p5 is imported. then i import the draw and setup (and maybe more) functions to the p5.py module. both can work. with my way the sketch looks a bit neater without the decorators, you's might be easier to handle in the p5.py module. I'm not sure which is best but i thought i'd let you know. you can remove this issue when you read it i think.

Also: i have got someone who wants to help too!

**Comment by jonay2000** [comment]
this is the code i have in my pyglet version https://github.com/jonay2000/p5.py. it seems not much but many functions i already made for the tkinter version so ill add those soon.

**Comment by abhikpal** [comment]
> i look back in the stack and find from where p5 is imported.

Thinking about something simiar mylsef still haven't implemented the code that will run sketches, though.

> Also: i have got someone who wants to help too!

:+1:

> this is the code i have in my pyglet version https://github.com/jonay2000/p5.py

I'll take  a look!
